name: runnable-cli
on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [
          "3.5",
          "3.6",
          "3.7",
          "3.8",
          "3.9",
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Runnable with CLI
        run: |
          # able to run cli
          pip install .
          python -m promptpay qrcode --id="0841234567"
          python -m promptpay qrcode --id="0841234567" --show=true
          python -m promptpay qrcode --id="0841234567" --file="./qrcode-cli.png"
          python -m promptpay qrcode --id="0841234567" --amount=2.34 --file="/tmp/qrcode-cli-with-amount.png"
